VERSION = "v1.0.1"
DESCRIPTION = f"域名批量检查工具 {VERSION}"

CLI_HELP_MESSAGE = "显示此帮助信息并退出程序"
CLI_HELP_INPUT = "指定输入文件，默认为 input.txt"
CLI_HELP_OUTPUT = "指定保存过期域名的文件"
CLI_HELP_ERROR = "指定保存未能成功查询的域名的文件"
CLI_HELP_NUM_PROCESSES = "指定并发进程数。默认为 1"
CLI_HELP_NUM_THREADS = "指定每进程最大并发线程数。默认为 80"
CLI_HELP_UNLOCK_THREADS_LIMIT = "解除线程最大值限制。--unlock-threads-limit 或 --unlock-threads-limit True 均可启用此选项"
CLI_HELP_QUIET = "使程序减少输出。--quiet 或 --quiet True 均可启用此选项"

INFO_NOT_REGISTER = "❌ {domain}  ⚪ Not Register"
INFO_NOT_FOUND_DATE = "⚠️ {domain}  🤔 Not Found Date"
INFO_ERROR_PARSING_DATE = "⚠️ {domain}  💻 Error Parsing Date"
INFO_EXPIRED = "❌ {domain}  🕐 Expired"
INFO_NOT_EXPIRED = "✅ {domain}  🆗 Not Expired"
INFO_INTERNET_ERROR = "⚠️ {domain}  🛜 Internet Error"
INFO_API_LIMIT = "⚠️ {domain}  🚫 API Limit"
