name: Build get-whois-server-list

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt

      - name: Install dependencies
        run: |
          pip install -r extra-scripts/get-whois-server-list/requirements.txt

      - name: Build Executable with Nuitka on Linux
        if: matrix.os == 'ubuntu-latest'
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: extra-scripts/get-whois-server-list/main.py
          mode: app

      - name: Build Executable with Nuitka on macOS
        if: matrix.os == 'macos-latest'
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: extra-scripts/get-whois-server-list/main.py
          mode: app

      - name: Build Executable with Nuitka on Windows
        if: matrix.os == 'windows-latest'
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: extra-scripts/get-whois-server-list/main.py
          mode: app

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Binary-${{ runner.os }}-${{ runner.arch }}-get-whois-server-list
          path: |
            build/*.exe
            build/*.bin
            build/*.app/**/*
          include-hidden-files: true
          compression-level: 9
